name: dio_http_cache
description: http cache lib for Flutter dio like RxCache.It use sqflite as disk cache,and google/quiver-dart/LRU strategy as memory cache.
version: 0.3.1
homepage: https://github.com/ashiq-mvp/dio_http_cache.git

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  crypto: ^3.0.5
  dio: ^5.7.0
  flutter:
    sdk: flutter
  json_serializable: ^6.8.0
  json_annotation: ^4.9.0
  path: ^1.9.0
  quiver: ^3.2.2
  sqflite: ^2.3.3+2

dev_dependencies:
  build_runner: ^2.4.13
  flutter_test:
    sdk: flutter

flutter:
  module:
    androidX: true
